    version: '3.3'

    services:
      db:
        image: mysql:5.7
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: life
          MYSQL_DATABASE: ideal
          MYSQL_USER: root
          MYSQL_PASSWORD: life

      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_ARBITRARY=1
        links:
          - db
        ports:
          - 7000:80
        volumes:
          - /sessions


      api:
        depends_on:
          - db
        build: .
        volumes:
          - ./:/var/www/html/
        ports:
          - "3030:80"
